server:
  port: 4040

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/oauth?serverTimezone=UTC&characterEncording=UTF-8
        username: root
        password: root
    security:
      oauth2:
        client:
          registration:
            github:
              clientId: c196fab610f4ab7cfc5b
              clientSecret: 4f435a03713798a86466ba19ab81f5307e39b55a
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
      provider:
        github: 
          autorization-uri: https://github.com/login/oauth/authorize
          token-uri: https://github.com/login/oauth/access_token
          user-info-uri: https://api.github.com/user

