server:
  port: 4040

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/oauth?serverTimezone=UTC&characterEncording=UTF-8
        username: root
        password: root
    security:
      oauth2:
        client:
          registration:
            github:
              clientId: 5bba39d62b7e1816a4f3
              clientSecret: 48c506fa989a21109ba45cfddf01b5ef85433b3b
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
      provider:
        github: 
          autorization-uri: https://github.com/login/oauth/authorize
          token-uri: https://github.com/login/oauth/access_token
          user-info-uri: https://api.github.com/user

